#server.port={cipher}{key:mykey}AQAbYylsZhOJFpV3KBht2U0VA1q4njiARpaZlOUlATSohvAyBnWFe1OR6Go66eKoSnM32iziVSFEGnpl1gJDs4z60joyJebPvA/QahIrK+qpgZuv8MHnaEYm/yhsAtV/fcSD29auZEtLOAYhK5gzB5zgXRJJ5HIqI5wIEcQuq2ls+KgX11+6tjE4rn+Cbx7wgyTaW+cj8L1SuW9bf8XMW2UbIaNal9wzlEkv2FLxJCcB+XmOu3Kw8DmWVM94lQFdBQ6gC1+M8bEfYoqtTBADyMmVq5WpZQKRLo5Js24wtWoPl+DZ5G17sTuO2Sf3eZ3v1aNXy5MLEFgRYfBbAlT9xuWnYNeXxpAOh/iIls8C0YTSbxY4bTmf4eXrDCjB6Wzhlb4=
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

#incicates the duration the server waits since it received the last heartbeat before it can evict an instance from its registry
eureka.instance.lease-expiration-duration-in-seconds=20

#actuator endpoint
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

logging.file.name=logs/discovery.log
logging.level.root=INFO
