#server.port={cipher}{key:mykey}AQBHJdOwqUftJJGtNx6FSCKeWP77nKwSErurEVSz8gb4iW4NijYdKUDASsTowwmzHKKSLWw1BT5cHJscOxGTrFq/ClsOARm6kULi2pySX3ThMTrdq1Zrs79eLiNEJozZiOBxUSSnDzIOvtIs9LrNKN24GrFPh3vJ+EUkrSLjO25dOoauhvmwVYJ/dbjQIT3l6dd2xAECm5ahhEz3cKz9lBpL4KDBGfY5T3PurqY7Aw/5Y0he/Q06drq1/aJdWo6TRuQj3Led1F7awVoXf/LPe1LIytk9yohRq7tD0fqm3gfMnl9cmMQlfGJcPSfPTYusvtTqrDqrEHc8EVwKqL1lMeQF2pRXBegN5OcOGJx4tHQZdyj+qNYVBK0tV7L5xBbTRkA=
server.port=8200

spring.cloud.gateway.routes[0].id=weatherModule
spring.cloud.gateway.routes[0].uri=lb://search
spring.cloud.gateway.routes[0].predicates[0]=Path=/weather/**

spring.cloud.gateway.routes[1].id=detailsModule
spring.cloud.gateway.routes[1].uri=lb://details
spring.cloud.gateway.routes[1].predicates[0]=Path=/details/**
#spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# ADD: route to student-management-service
spring.cloud.gateway.routes[2].id=studentService
spring.cloud.gateway.routes[2].uri=lb://student-management-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/student/**
# Optional: remove /student from path

spring.cloud.gateway.discovery.locator.enabled=true

myservice.ribbon.NFLoadBalancerRuleClassName=com.netflix.loadbalancer.RandomRule

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
#eureka.client.registryFetchIntervalSeconds=xx
#ribbon.ServerListRefreshInterval

#indicates the frequency the client sends heartbeat to server to indicate that it is alive.
eureka.instance.lease-renewal-interval-in-seconds=10

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

#actuator endpoint
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
