#server.port={cipher}{key:mykey}AQAEjxhGs+ejLu6l9k09E9MGse37CJoINL3qYTVEjDr/OFQ78W+zAnS6RFe20AfnIEsTxzwu30LJ3DWlKZp6p73rWE37sCpjdF7SCdr613M8+PNjnHQW6sgYrRxRrcDKipd0qSemqQ0xFm+2d6AescP74vnemD66ePjZnQH3dxDjk85eHtPWlNvV4nW9xJ3DeQT9fhjw7ft58pHPYT7LsPYrLpNe2rHUqP2SBTkpu7VhDvP6jNPEU6283wqUN7IWb1e+ypdfVRAb0kZdNDZ4iXlBIqYrQU0BP3pHRk+rXUgexPzhHzgLbwpJpqf+wrftA9llApHocyW42yD9AoEETR+VPsh5nAcrVfd5sK8/s3m7K9suSsd66Rq1ftdkm0SrOJA=

server.port=8080

spring.application.name=student-management-service
# MariaDB connection URL
spring.datasource.url=jdbc:mariadb://localhost:3306/student_db

# Database username
spring.datasource.username={cipher}{key:mykey}AQAczaNHLXGa5kFxmVbevavlpZqTlW7/1QFiK5jHb0Zeg5qMJo68AXJVEwWaI99wrEr4+E+wrHFaqwt8Xz27buJB9cvnmUJNQVin71GhiFXYSXQZzv7UxXWNFpWszgFZBVbEsztkfzuqrjZ3qzVCf6TTo5c9Uwg4ZoljDsmSzrEvBnkOLCJIHaEKP7viagCEpTj9QAP/XcAWsdoKEC0WoCb0kvNLPEzgh9sHx22svoeIZFohOQim9TmAz8EunotAW4va7bMWHKu3hbKd2wYA++MaHjTkmq84ZMpXx0DvtBk492Ig1arnIF0OxPMu+cfdzPpVMl/C91EEOjqVOc+Hq9cdF0dVBVmP/qyKALD6IO2Yg/bXM/e9Mfq6L5jOA3Vkij4=

# Database password(did not set password for this database for the student management service before)
spring.datasource.password=

spring.docker.compose.enabled=false

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

#actuator endpoint
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

logging.file.name=logs/student.log
logging.level.root=INFO
